services:
  prometheus-process-exporter:
    restart: always
    image: whatwewant/prometheus-process-exporter:${SERVICE_PROMETHEUS_PROCESS_EXPORTER_IMAGE_VERSION}
    ports:
      - 0.0.0.0:${SERVICE_PROMETHEUS_PROCESS_EXPORTER_PORT}:9256
    privileged: true
    volumes:
      - /proc:/host/proc:ro
    mem_limit: 4096m
    cpus: 2
      
networks:
  default:
    external: true
    name: compose-ingress
